### ISSUE TITLE
Blender 4.1: Issue with the Tissue

### ISSUE THREAD

**Issue by johndow16** [alessandro-zomparelli/tissue#154]
HI there, there are some issues with the Tissue add-on in Blender 4.1. Version 3.5.4 does work in Blender 4.1 but produces some errors. Here are a few that I found so far...

- Created mesh can not be updated. When you press "Refresh" the add-on says "Can't Tessellate :-("

- Material-based approach doesn't work. Here are the errors:

Ver 3.5.4

```
Error: Python: Traceback (most recent call last):
  File "I:\Graphics\Blender 4.1\4.1\scripts\addons\mesh_tissue\tessellate_numpy.py", line 2108, in execute
    new_ob = join_objects(same_iteration)
  File "I:\Graphics\Blender 4.1\4.1\scripts\addons\mesh_tissue\utils.py", line 327, in join_objects
    bpy.ops.object.join(override)
  File "I:\Graphics\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "I:\Graphics\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: I:\Graphics\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

Ver 3.6.0 dev doesn't work in Blender 4.1 at all. Here is the error:

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\tessellate_numpy.py", line 2173, in execute
    same_iteration = tessellate_patch(props)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\tessellate_numpy.py", line 209, in tessellate_patch
    elif fill_mode == 'QUAD': ob0 = reduce_to_quads(_ob0, _props)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\tessellate_numpy.py", line 3609, in reduce_to_quads
    new_ob = convert_object_to_mesh(ob, props['gen_modifiers'], True, props['rotation_mode']!='UV')
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\utils.py", line 266, in convert_object_to_mesh
    new_me = simple_to_mesh_mirror(ob)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\utils.py", line 351, in simple_to_mesh_mirror
    me = simple_to_mesh(ob, depsgraph)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tissue-b360-dev\utils.py", line 367, in simple_to_mesh
    me.calc_normals()
AttributeError: 'Mesh' object has no attribute 'calc_normals'. Did you mean: 'flip_normals'?
Location: I:\Graphics\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
```

**Comment by alessandro-zomparelli** [comment]
Hi @johndow16 thank you for reporting this issue. I'm working on an update fo the code for Blender 4 :-)

**Comment by alessandro-zomparelli** [comment]
Hi @johndow16 I updated the master branch, please let me know if it works properly now.
Thanks

Alessandro

**Comment by johndow16** [comment]
Hi @alessandro-zomparelli Thank you. I've checked the new version (3.6.2) and it works in Blender 4.1 👍 But... sometimes when I use 'material-based approach' it does everything properly, yet shows me a warning saying: "Can't find any object according to the material names". I've also encountered a bug where some faces are "rotated" 90 degrees, but I think I saw this one somewhere before.

**Comment by alessandro-zomparelli** [comment]
Hi @johndow16 this does not seem a bug, the rotation of the components depends on the indexes of the vertices of the faces. If needed you can also manually rotate the faces that you want to change by using the rotate operators:  
![image](https://github.com/alessandro-zomparelli/tissue/assets/6708848/36dc1683-06c6-4edb-91c7-1ae526fa82af)
Regarding the problem with the material-based components, do all the materials in your base object correspond with some component object names?

**Comment by johndow16** [comment]
@alessandro-zomparelli within the next few days I'll make and upload a scene to show you both issues at the same time.

**Comment by johndow16** [comment]
@alessandro-zomparelli Hi, here is the scene. 

How to use it and what you will see:

1. Use "Components from Materials" on the 'BaseMesh 01'. The end result will be exactly what it should be, yet in the lower left corner you will see a warning windows saying "Can't find any object according to the material names".

2. Use "Components from Materials" on the 'BaseMesh 02'. You'll see that warning again and on top of that half of the resulted mesh will have rotated faces.

[Tissue_Test_Scene.zip](https://github.com/alessandro-zomparelli/tissue/files/13550154/Tissue_Test_Scene.zip)

**Comment by johndow16** [comment]
@alessandro-zomparelli here is a video where I demonstrate the first 'bug':

https://github.com/alessandro-zomparelli/tissue/assets/75545135/4b3d4587-750b-4f88-a56a-2702740521b2

When it comes to the rotated faces I still don't understand why when I use 'BaseMesh 01' I get desired result (no rotated faces, etc.), while using 'BaseMesh 02' gives me rotated faces on half of the mesh.

**Comment by alessandro-zomparelli** [comment]
Hi @johndow16 
1) Yes, you are right, I didn't notice that, it is a bug, but it's not affecting the result, it is just a false positive because is running the check on the final object, instead of the base mesh. I have to fix that.
2) Yes, the way you model it affects the indices, it is not a bug of Blender or Tissue, just how it works. This is why I added the rotate faces option and the active UV method. To be accurate, the indices are creating a U shape and not a Z, as you draw them and their orientation affect the normal direction. For a normal pointing upward, they should be counterclockwise:
![image](https://github.com/alessandro-zomparelli/tissue/assets/6708848/10b76233-2cd0-4192-a098-1ef8f892b1f8)

**Comment by johndow16** [comment]
Hi @alessandro-zomparelli I'm a bit confused. On your picture 0->1->2->3 create a U shape, but in Blender 0->1->2->3 create a Z shape.

**Comment by alessandro-zomparelli** [comment]
How can you tell that they create a Z? The vertices indexes are not relevant, what matters is their order when stored by the face.

**Comment by johndow16** [comment]
Seems like I misunderstood the concept of indices. I thought they were used to control in what order the vertices are received in. 

"You live, you learn." :)

**Comment by alessandro-zomparelli** [comment]
If you run this in the terminal, you will see how your vertices are used by every face:

```
import bpy
for face in bpy.context.object.data.polygons:
    print(list(face.vertices))
```

this is the result that I get from the default cube:

```
[0, 4, 6, 2]
[3, 2, 6, 7]
[7, 6, 4, 5]
[5, 1, 3, 7]
[1, 0, 2, 3]
[5, 4, 0, 1]  
```

**Comment by johndow16** [comment]
I was reflecting on why I got the concept of indices it wrong and realized, that when I was watching a series of lectures on rendering, the guy there used 'connect the dots' picture game example for the indices. I guess that example got stuck in my head :)

PS. He used something like this one:
![connect-the-dots](https://github.com/alessandro-zomparelli/tissue/assets/75545135/32d78a36-0a0e-49dc-aeed-d8a370d7595a)

**Comment by ansodhani** [comment]
@alessandro-zomparelli Hi, I am facing the same issue as @johndow16 with the material-based approach, but in my case, it doesn't work at all, much less show the warning. I am using blender 4.0.2 and tissue 3.7.0

**Comment by alessandro-zomparelli** [comment]
Hi @ansodhani have you tried using the latest version of both Tissue and Blender?
